/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: [
    'postcss-import',
    'tailwindcss',
    'autoprefixer',
    [
      require.resolve('./postcss-radix-theme-purge'),
      {
        selectors: [
          '.dark',
          '.rt-Kbd',
          '.rt-Callout',
          '.rt-BaseCheckbox',
          '.rt-Checkbox',
          '.rt-ContextMenu',
          '.rt-DataList',
          '.rt-BaseDialog',
          '.rt-HoverCard',
          '.rt-Inset',
          '.rt-Popover',
          '.rt-Progress',
          '.rt-BaseRadio',
          '.rt-Radio',
          '.rt-ScrollArea',
          '.rt-SegmentedControl',
          '.rt-Select',
          '.rt-Separator',
          '.rt-Skeleton',
          '.rt-Slider',
          '.rt-Spinner',
          '.rt-Switch',
          '.rt-Table',
          '.rt-BaseTabList',
          '.rt-Tabs',
          '.rt-TabNav',
          '.rt-TextArea',
          '.rt-TextField',
          '.rt-ThemePanel',
          "[data-accent-color='bronze']",
          "[data-accent-color='brown']",
          "[data-accent-color='crimson']",
          "[data-accent-color='grass']",
          "[data-accent-color='green']",
          "[data-accent-color='iris']",
          "[data-accent-color='mint']",
          "[data-accent-color='orange']",
          "[data-accent-color='pink']",
          "[data-accent-color='plum']",
          "[data-accent-color='purple']",
          "[data-accent-color='red']",
          "[data-accent-color='sky']",
          "[data-accent-color='teal']",
          "[data-accent-color='tomato']",
          "[data-accent-color='yellow']",
          "[data-accent-color='mauve']",
          "[data-accent-color='olive']",
          "[data-accent-color='sage']",
          "[data-accent-color='sand']",
        ],
        fontFamilies: [
          'Segoe UI (Custom)',
          'Open Sans (Custom)',
          'Consolas (Custom)',
        ],
      },
    ],
  ],
};

module.exports = config;
