import { Metadata } from "next";
import { Rubik } from "next/font/google";
import { FC, PropsWithChildren } from "react";

import Analytics from "./analytics";
import Providers from "./providers";

const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <html lang="en" className={rubik.variable}>
    <body>
      <Providers>{children}</Providers>
      <Analytics />
    </body>
  </html>
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default RootLayout;
