import '@mantine/core/styles.css'; // TODO: consider import individual CSS files instead

import { ColorSchemeScript, MantineProvider, createTheme } from '@mantine/core';
import type { Metadata } from 'next';
import { Geist, Geist_Mono as GeistMono } from 'next/font/google';
import { type FC, type PropsWithChildren } from 'react';

import { Header } from '@/components/header';

const geist = Geist({ subsets: ['latin'] });
const geistMono = GeistMono({ subsets: ['latin'], preload: false });

const theme = createTheme({
  fontFamily: geist.style.fontFamily,
  fontFamilyMonospace: geistMono.style.fontFamily,
  primaryColor: 'deep-blue',
  colors: {
    'deep-blue': [
      '#ecefff',
      '#d5dafb',
      '#a9b1f1',
      '#7a87e9',
      '#5362e1',
      '#3a4bdd',
      '#2c40dc',
      '#1f32c4',
      '#182cb0',
      '#0a259c',
    ],
  },
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <html suppressHydrationWarning lang="en">
    <head>
      <ColorSchemeScript />
    </head>
    <body>
      <MantineProvider theme={theme}>
        <Header />
        {children}
      </MantineProvider>
    </body>
  </html>
);

export default RootLayout;
