import {
  SiContentful,
  SiDatacamp,
  SiEnterprisedb,
  SiGithub,
  SiGoogle,
  SiImprovmx,
  SiLinkedin,
  SiMicrosoft,
  SiMongodb,
  SiMui,
  SiNextdotjs,
  SiOracle,
  SiPlanetscale,
  SiPrisma,
  SiReact,
  SiReacthookform,
  SiStackoverflow,
  SiTypescript,
  SiUdemy,
  SiVercel,
  SiYoutube,
  SiZod,
} from '@icons-pack/react-simple-icons';
import {
  BrainCircuit,
  Bug,
  Database,
  LayoutDashboard,
  MessagesSquare,
  MonitorDot,
  TabletSmartphone,
  Terminal,
  Workflow,
} from 'lucide-react';
import { LiteralUnion } from 'type-fest';

import { SiFormspree } from '@/components/icons/si-formspree';
import * as contentfulIds from '@/constants/contentful-ids';

const Icons = {
  [contentfulIds.dataCamp]: SiDatacamp,
  [contentfulIds.enterpriseDb]: SiEnterprisedb,
  [contentfulIds.github]: SiGithub,
  [contentfulIds.google]: SiGoogle,
  [contentfulIds.linkedin]: SiLinkedin,
  [contentfulIds.microsoft]: SiMicrosoft,
  [contentfulIds.mongodb]: SiMongodb,
  [contentfulIds.oracle]: SiOracle,
  [contentfulIds.stackOverflow]: SiStackoverflow,
  [contentfulIds.udemy]: SiUdemy,
  [contentfulIds.youtube]: SiYoutube,
  [contentfulIds.backend]: Terminal,
  [contentfulIds.cms]: MonitorDot,
  [contentfulIds.database]: Database,
  [contentfulIds.devOps]: Workflow,
  [contentfulIds.frontend]: LayoutDashboard,
  [contentfulIds.machineLearning]: BrainCircuit,
  [contentfulIds.mobile]: TabletSmartphone,
  [contentfulIds.qa]: Bug,
  [contentfulIds.softSkills]: MessagesSquare,
  [contentfulIds.react]: SiReact,
  [contentfulIds.nextJs]: SiNextdotjs,
  [contentfulIds.typescript]: SiTypescript,
  [contentfulIds.joyUi]: SiMui,
  [contentfulIds.reactHookForm]: SiReacthookform,
  [contentfulIds.zod]: SiZod,
  [contentfulIds.prisma]: SiPrisma,
  [contentfulIds.planetScale]: SiPlanetscale,
  [contentfulIds.vercel]: SiVercel,
  [contentfulIds.contentful]: SiContentful,
  [contentfulIds.formspree]: SiFormspree,
  [contentfulIds.improvMx]: SiImprovmx,
};

export const getIconByContentfulId = (
  id: LiteralUnion<keyof typeof Icons, string>,
) => (id in Icons ? Icons[id as keyof typeof Icons] : undefined);
