name: E2E
on: deployment_status

jobs:
  e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, edge, firefox, webkit]
    steps:
      - run: echo $GITHUB_REF
      - run: echo ${{ github.event.deployment.ref }}
      - run: export GITHUB_REF="${{ github.event.deployment.ref }}"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install-deps webkit
        if: matrix.browser == 'webkit'
      - uses: cypress-io/github-action@v6
        with:
          install: false
          browser: ${{ matrix.browser }}
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.environment_url }}
