name: E2E
on: deployment_status

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, edge, firefox, webkit]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.environment_url }}
