name: Unlighthouse
on: deployment_status

jobs:
  unlighthouse:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @unlighthouse/cli puppeteer
      # FIXME: scanner.* config is currently not respected by unlighthouse-ci, specifying it with CLI option instead
      - run: |
          unlighthouse-ci \
          --site ${{ github.event.deployment_status.environment_url }} \
          --throttle
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          path: ./.unlighthouse
