name: Unlighthouse
on: deployment_status

jobs:
  unlighthouse:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @unlighthouse/cli puppeteer
      # FIXME: --samples is currently bugged in Lighthouse v9, manually bumping to v11 as a workaround
      - name: Bump Lighthouse Version
        run: |
          global_node_modules=$(npm root -g)
          cd $(global_node_modules)/@unlighthouse/cli
          cd ./node_modules/@unlighthouse/core
          sed -i 's/"lighthouse": "^9.6.8"/"lighthouse": "^11.5.0"/' package.json
          cd $(global_node_modules)/@unlighthouse/cli
          npm install
          cd ./node_modules/@unlighthouse/core/dist
          sed -i 's/lighthouse-core/core/' index.mjs
      # FIXME: --throttle is not recognized when specified in config file, specifying it with CLI option instead
      - run: |
          unlighthouse-ci \
          --site ${{ github.event.deployment_status.environment_url }} \
          --throttle \
          --samples 5
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          path: ./.unlighthouse
