name: E2E
on: deployment_status

jobs:
  e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm install -g @unlighthouse/cli puppeteer
      - run: |
          unlighthouse-ci \
            --site ${{ github.event.deployment_status.environment_url }} \
            --budget 90 \
            --no-cache \
            --throttle \
            --samples 3
