name: Unlighthouse
on: deployment_status

jobs:
  unlighthouse:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    environment: ${{ github.event.deployment_status.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @unlighthouse/cli puppeteer
      # FIXME: --samples is currently bugged, set it to 3 when unlighthouse is using lighthouse v10+
      # FIXME: --throttle is not recognized when specified in config file, specifying it with CLI option instead
      - run: |
          unlighthouse-ci \
          --site ${{ github.event.deployment_status.environment_url }} \
          --throttle
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          path: .unlighthouse
