name: Unlighthouse
on: deployment_status

jobs:
  unlighthouse:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g @unlighthouse/cli puppeteer
      - run: |
          unlighthouse-ci \
            --site ${{ github.event.deployment_status.environment_url }} \
            --reporter jsonExpanded \
            --budget 80 \
            --no-cache \
            --throttle
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          path: ./.unlighthouse/ci-result.json
